### ISSUE TITLE
[GCP] Pretty Print IAM Policy in log messages

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kfctl#104]
We have lots of log messages like the following

https://github.com/kubeflow/kfctl/blob/90fed64eedae58d5ca88eb04715614be1bcdda8b/pkg/kfapp/gcp/gcp.go#L1662

Which ends up generating output like this

```
INFO[0420] New policy: {[] [0xc0009842a0] ACAB 1 {200 map[Alt-Svc:[quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000] Cache-Control:[private] Content-Type:[application/json; charset=UTF-8] Date:[Fri, 22 Nov 2019 03:28:52 GMT] Server:[ESF] Vary:[Origin X-Origin Referer] X-Content-Type-Options:[nosniff] X-Frame-Options:[SAMEORIGIN] X-Xss-Protection:[0]]} [] []}  filename="gcp/gcp.go:1702"
```

This is hard to read for a couple reasons

1. We aren't including field names when we print out the struct
1. We aren't recursively evaluating pointers in the struct which is why we have addresses like [0xc0009842a0] 

We should fix this by dumping the struct to json or yaml and then printing that ; we can use
https://github.com/kubeflow/kfctl/blob/3ec1c55f9bcca127e655a6b9182e1f01d87b0eec/pkg/utils/logging.go#L10

**Comment by PatrickXYS** [comment]
Since GCP has migrated out of kfctl and use gcp-blueprint instead, close the issue

/close
