### ISSUE TITLE
kfctl delete is not idempotent

### ISSUE THREAD

**Issue by gabrielwen** [kubeflow/kfctl#119]
Way to reproduce:
- Run `kfctl delete`
- Interrupt in the middle of something, for example, during deployment deletion.
- Run `kfctl delete` again.

Error:
`Error: couldn't delete KfApp:  (kubeflow.error): Code 500 with message: kfApp Delete failed for kustomize:  (kubeflow.error): Code 400 with message: couldn't delete customresourcedefinitions Error: Delete https:/
/35.231.48.73/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions?labelSelector=app.kubernetes.io%2Fname%3Dd-test: dial tcp 35.231.48.73:443: connect: connection refused`

also witness some errors about namespace.

**Comment by jlewi** [comment]
@gabrielwen has a PR pending in #110 

There was a bunch of discussion (see #110)  but I think we ultimately settled on using the metadata field clusterName.

**Comment by jlewi** [comment]
#110 was merged. That should ensure we check that we are running against the correct cluster but I'm not sure that alone fixes idempotency.

Do we have a delete test?

We should try it out and see if there are still bugs with idempotency and if not close this issue.

**Comment by jlewi** [comment]
It looks like we have an E2E test for deletion
https://github.com/kubeflow/kfctl/blob/331fb9d02799e6453b7c7924bfc4cc88817ad9cb/py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py#L457

https://github.com/kubeflow/kfctl/blob/master/py/kubeflow/kfctl/testing/pytests/kfctl_delete_wrong_cluster.py

So I'm going to close this as fixed.
