### ISSUE TITLE
kfctl on GCP: skip GPU node pool if no GPU available on target zone.

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kfctl#121]
Currently we create GPU node pool by default:
https://github.com/kubeflow/manifests/blob/5bd82ecc8d5e449bcf83c30ba7e74731dd8584f1/gcp/deployment_manager_configs/cluster-kubeflow.yaml#L63

This might block user when they try to deploy on zones without GPU resource.

Before `apply` action, kfctl should set `gpu-pool-max-nodes` to 0 when target zone is not one of following:
```
us-west1-b
us-central1-a
us-central1-c
us-east1-c
us-east1-d
europe-west1-b
europe-west1-d
asia-east1-a
asia-east1-b
```

**Comment by jlewi** [comment]
@kunmingg could you triage this issue please?
https://github.com/kubeflow/community/blob/master/proposals/issue_triage.md
