### ISSUE TITLE
Release Kubeflow 0.7.1

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kfctl#124]
Tracking bug for 0.7.1.

Issues we want fixed in 0.7.1

* kubeflow/kfserving#568 - KFServing mutating webhook is causing problems.

Before we can start cherry-picking changes to Kubeflow manifests onto the v0.7-branch we need to pin the version of kubeflow/manifests used in the v0.7.0 KFDef YAML specs (kubeflow/manifests#643)

To fix kubeflow/kfserving#568 there are a number of things that need to happen see
https://github.com/kubeflow/kfserving/issues/568#issuecomment-561974987

**Comment by jlewi** [comment]
@lluunn can you help with this since you are buildcop this week?

**Comment by jlewi** [comment]
@zhenghuiwang Can you help with this. I think the next steps are 

1. Building an updated profile controller image. 
1. Updating the profile controller manifest on master to use that image
1. Cherry-picking that change onto the v0.7-branch of manifests

**Comment by jlewi** [comment]
Looks like the profile controller image on master was updated in kubeflow/manifests#646.

Do we need to cherry-pick it into the v0.7-branch?

**Comment by lluunn** [comment]
Already cherrypick: https://github.com/kubeflow/manifests/pull/649

**Comment by lluunn** [comment]
I tried the 0.7 kfctl (same as before) with the new 0.7.1 kfdef: https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_gcp_iap.0.7.1.yaml.
Deployment succeeded, endpoint is accessible, and I can create and connect to a notebook.

**Comment by jlewi** [comment]
Thanks @lluunn . 

Should we update the docs https://www.kubeflow.org/docs/gke/deploy/deploy-cli/ to use 0.7.1?

**Comment by jlewi** [comment]
@gabrielwen what did we decide last week about doing a kfctl 0.7.1 release?

**Comment by gabrielwen** [comment]
> @gabrielwen what did we decide last week about doing a kfctl 0.7.1 release?

We've decided not to cherrypick a semantic change to `kfctl delete` and leave that to 1.0

However, I think 2 of the changes are worth being cherrypicked: #144 #145 
WDYT?

**Comment by lluunn** [comment]
update doc in https://github.com/kubeflow/website/pull/1466

**Comment by jlewi** [comment]
So it looks like the website has been updated to use 0.7.1 YAML configs.

It looks like we still need to cut a 0.7.1 kfctl binary. It looks like all the fixes @gabrielwen have mentioned have been cherry-picked.
