### ISSUE TITLE
small tweak to kfctl init usage msg: clarify local path for --config

### ISSUE THREAD

**Issue by amygdala** [kubeflow/kfctl#15]
I found that when passing a local file to the `--config` arg, I needed to use the full path (otherwise, got this error: `relative paths require a module with a pwd`). The usage info doesn't indicate that clearly enough.  Instead of:

```
Usage:
  kfctl init <[path/]name> [flags]

Flags:
      --config string            Static config file to use. Can be either a local path or a URL.
                                 For example:
                                 --config=https://raw.githubusercontent.com/kubeflow/kubeflow/master/bootstrap/config/kfctl_platform_existing.yaml
                                 --config=kfctl_platform_gcp.yaml
```

we might want to show something like `--config=/your/local/path/to/kfctl_platform_gcp.yaml`
The repo README should be updated as well if so.

**Comment by PatrickXYS** [comment]
Since GCP has migrated out of kfctl and use gcp-blueprint instead, close the issue

/close
