### ISSUE TITLE
kfctl should work with private GKE without public endpoint

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kfctl#158]
kfctl should work with private GKE without public endpoint.
How to setup test env:
1. create private GKE without public endpoint
2. in same VPC, create VM without public network access
3. in same VPC, enable private GCP access
4. verify running kfctl from the VM to deploy to target private GKE.

**Comment by kunmingg** [comment]
TODOs:

1. make kubeflow images accessible from private GKE: some images used by kubeflow is not hosted on GCR so is not accessible from private GKE. To resolve it we have 2 options:
 * option 1: provide image replication tool which can sync images to client project 
 * option 2: replicate images to kubeflow images project and create private GKE overlays which use images only from GCR

2. release private GKE compatible IAP kubeflow config file `kfctl_gcp_iap_private.yaml`: this config file should support:
 * deploy to existing private GKE.
 * create an IAP endpoint through which user can access kubeflow UI.
 * if kfctl is running from a private VM, private google access should be enabled.

**Comment by PatrickXYS** [comment]
Since GCP has migrated out of kfctl and use gcp-blueprint instead, close the issue

/close
