### ISSUE TITLE
Release 0.7.2 binaries 

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/kfctl#178]
Could release team help build binaries for 
https://github.com/kubeflow/kfctl/releases/tag/v0.7.2-rc.0
 and update the release?  We meet some installation problems here. https://github.com/kubeflow/kubeflow/issues/4642 Our workshop users do not have knowledge on golang and they are not able to build binaries themselves. 

/cc @kunmingg

**Comment by jlewi** [comment]
Obsolete since we are in the process of releasing 1.0
