### ISSUE TITLE
KFCTL 1.0 tracking

### ISSUE THREAD

**Issue by gabrielwen** [kubeflow/kfctl#18]
# Requirements
| Descriptions | Category | Status | Issue
|--------------|----------|--------|------
| Upgradability | Required | **WIP** | kubeflow/kubeflow#3727
| New semantics for KFCTL (build/apply) | Required | **DONE** | #19
| Backward compatibility for KfDef | Required | **DONE** | kubeflow/kubeflow#4002
| Reconcile for KFCTL | Recommended | **NOT_STARTED** | kubeflow/kubeflow#4056
| Plugin injections | Recommended | **NOT_STARTED** | kubeflow/kubeflow#3708
| CI/CD | Required | **WIP** | #24 
| Logging | Recommended | **NOT_STARTED** | kubeflow/kubeflow#3671

## New Semantics
We'd like to introduce new semantics `kfctl build/apply`: [link](https://docs.google.com/document/d/1kviNOdjoBPeoJ56KBvMKWq7SzrSN5rFUQoULK8muD-M/edit?ts=5d63c5c9#bookmark=id.iwxbmwl36xkz)

| Tasks | Category | Status | Issue
|------|--------|------|---------
| Add new flag `-f` | Required | **DONE** | #20
| `-f` should takes both local and remote files | Required | **DONE** | #21
| Implement `build` | Required | **DONE** | #22
| Implement `apply` | Required | **DONE** | #23

## Backward Compatibility for KfDef
| Tasks | Category | Status | Issue
|------|--------|------|---------
| Backward compatibility | Required | **DONE** | kubeflow/kubeflow#4002

## Reconcile for KFCTL
| Tasks | Category | Status | Issue
|------|--------|------|---------
| Implement Reconcile semantics | Recommended | **NOT_STARTED** | kubeflow/kubeflow#4056

## Plugin injections
kubeflow/kubeflow#3708

## CI/CD
| Tasks | Category | Status | Issue
|------|--------|------|---------
| E2E Test | Required | **DONE** | #25
| Unit tests coverage | Required | **Done** | #26
| nightly builds | Required | **NOT_STARTED** | kubeflow/kfctl#105
| Testing on config files | Recommended | **NOT_STARTED** | kubeflow/kubeflow#3688
| Release process | Required | **NOT_STARTED** | #27

## Logging
kubeflow/kubeflow#3671

## Docs
[kfctl Design Doc](http://bit.ly/kfctl_design)

**Comment by gabrielwen** [comment]
@jlewi @kkasravi @yanniszark I created this umbrella issue to track the status of kfctl v1beta1.  Please feel free to update anything that I missed or you could also comment here and I'll update it.

**Comment by jlewi** [comment]
@gabrielwen could we update this based on everything that got shipped in 0.7.0?

I think the new semantics are done: kubeflow/kubeflow#3518

**Comment by gabrielwen** [comment]
> @gabrielwen could we update this based on everything that got shipped in 0.7.0?
> 
> I think the new semantics are done: [kubeflow/kubeflow#3518](https://github.com/kubeflow/kubeflow/issues/3518)

updated.

**Comment by jlewi** [comment]
It looks like the manifests were updated to v1 in kubeflow/manifests#684.

It looks like the primary work remaining is CI/CD.

What is the status of the various test grids related to kfctl?

**Comment by jlewi** [comment]
For upgrades: we are waiting on an update to kubeflow/kubeflow#3727 to figure out remaining work.

* kubeflow/kfctl#24 is still tracking CI/CD work

* kubeflow/kfctl#26 is tracking unittests and is fixed.

* I changed Testing on Release configs kubeflow/kubeflow#3688 to Recommended since the issue is P2.

* For the release process kubeflow/kfctl#24 I left a comment in the issue to figure out the remaining work

**Comment by jlewi** [comment]
Closing this out as we have more specific issues.

For upgrades I still think we are saying this is Alpha for 1.0 so its not release blocking.
