### ISSUE TITLE
Kfctl implements new semantics tracking

### ISSUE THREAD

**Issue by gabrielwen** [kubeflow/kfctl#19]
- [ ] Add a new flag `-f` #20 
- [ ] `-f` takes both local and remote files #21
- [ ] Implements `build` #22
- [ ] Implements `apply` #23

**Comment by jlewi** [comment]
@gabrielwen Can we close this? I think this is implemented in v0.7.0?

Duplicate of kubeflow/kubeflow#3518 ?
