### ISSUE TITLE
pytorch job is flaky

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kfctl#199]
The pytorch job appears to be flaky

Example failure on presubmit
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_manifests/816/kubeflow-manifests-presubmit/1222997175437365248/

**Comment by jlewi** [comment]
Here's the code.
https://github.com/kubeflow/kfctl/blob/c5c55f6d1b79e285f28fa433d6e4e2e739cefb63/py/kubeflow/kfctl/testing/pytests/pytorch_job_deploy.py#L42

It looks like the problem is that the test submits the job and then immediately checks if the pods exist.

That seems like a race condition.

As a short term fix we can mark the test as expected to fail.

/cc @animeshsingh @Tomcli @johnugeorge @richardsliu

**Comment by PatrickXYS** [comment]
This issue should be solved by https://github.com/kubeflow/kfctl/pull/200

/close
