### ISSUE TITLE
kfctl kustomize secretGenerator is broken

### ISSUE THREAD

**Issue by WillBeebe** [kubeflow/kfctl#210]
Hi y'all. I was deploying master of the `kubeflow/manifests` and the metadata server wasn't coming up. The pod was stuck in a pending state trying to mount a secret that was not on the system. In the [metadata/overlays/db/kustomization.yaml](https://github.com/kubeflow/manifests/blob/master/metadata/overlays/db/kustomization.yaml#L12-L14) file that secret _should_ be generated by kustomize.

I ran `kustomize build ... | kubectl apply -f -` and that worked... After pawing through the source code a bit, I learned that kfctl does some merging of it's own beyond rending the overlays with kustomize. The `README.md` in the manifests repo also talks about this.

I added a test case for it, and to be expected it failed. After looking through the file I finally found the error. The key value is `secretGenerator` not `secretGeneratorMap`. After changing that the test passed! Leaving this issue here as a warning to anyone else who tries to deploy the master manifests until my PR is merged.

*You can make the changes I made and compile the binary yourself if you don't want to wait.

**Comment by jlewi** [comment]
This is amazing thank you.

/assign @zhenghuiwang 
/assign @gabrielwen

**Comment by zhenghuiwang** [comment]
@WillBeebe Thanks for filing this issue.

What kfctl binary do you use?

I think the issue you found was fixed by #187 but kfctl RC2 doesn't contain that fix. Your PR seems only renames a constant but doesn't change any logic. Am I missing something?

**Comment by WillBeebe** [comment]
@zhenghuiwang I was using the latest release from github 1.0.2 at the time. I also compiled a binary from source and tried it and the error is the same. The root cause is the key that is being saved to the kustomizationMaps => `kustomizationMaps[secretsMapGeneratorMap]` is the wrong key and not a kustomize key, changing that to `secretsGeneratorMap` fixes the issue. I haven't compiled and tested #187 but it's possible that change fixes this. I'll put down master now, add my test case and give it a shot.

**Comment by WillBeebe** [comment]
Confirming that #187 does fix this behavior. I trimmed my PR down to just adding the test case

**Comment by WillBeebe** [comment]
I should also mention, that when I was compiling from source I didn't have #187 locally. Before 187 my fix was needed, and now it's not. :)
