### ISSUE TITLE
kfctl build fails with Error opening a gzip reader

### ISSUE THREAD

**Issue by Julianxo** [kubeflow/kfctl#236]
/kind bug

**What steps did you take and what happened:**
I followed the tutorial for AWS setup on this page https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/.
I also followed this tutorial to setup TLS and AWS Cognito.

When i come to the step `kfctl build -V -f ${CONFIG_URI}` in 3 of 4 cases I get the following error:
Code 400 with message: couldn't download URI https://github.com/kubeflow/manifests/archive/v0.7-branch.tar.gz Error Error opening a gzip reader for /tmp/getter276108747/archive: EOF

**What did you expect to happen:**
I except the build to work in 4 of 4 cases or at least to be deterministic.

**Environment:**
Kubeflow version: 0.7.1
kfctl version: (use kfctl version): v0.7.1-2-g55f9b2a
Kubernetes platform: (e.g. minikube): AWS EKS
Kubernetes version: (use kubectl version): Client 1.16, Server 1.14
OS (e.g. from /etc/os-release): macOS Mojave 10.14.6

**Comment by Jeffwan** [comment]
@Julianxo 

Thanks a known issue for 0.7.1. Sorry for the problem, there's a walkaround for this issue. 
https://github.com/kubeflow/kfctl/issues/178

**Comment by Jeffwan** [comment]
Please try 1.0rc at this moment

**Comment by Julianxo** [comment]
I can confirm that it is fixed in 1.0rc, thanks.
