### ISSUE TITLE
Kubeflow operator should not delete namespace it did not create

### ISSUE THREAD

**Issue by vpavlin** [kubeflow/kfctl#241]
Quoting operator.md:

```
KUBEFLOW_NAMESPACE=kubeflow
kubectl create ns ${KUBEFLOW_NAMESPACE}
# kubectl create -f deploy/crds/kfdef_quota.yaml -n ${KUBEFLOW_NAMESPACE} # only deploy this if the k8s cluster is 1.15+ and has resource quota support
kubectl create -f <kfdef> -n ${KUBEFLOW_NAMESPACE}
```

When you do `oc delete -f <kfdef>` the operator deletes the namespace which it should not as it does not own it

**Comment by animeshsingh** [comment]
@vpavlin this needs to be implemented in two phases - we need kfclt to know what has been deployed,  and then be able to delete only what it has deployed. Will require adding owner reference. @adrian555 and @Tomcli will look at it

/assign @adrian555 @Tomcli

**Comment by adrian555** [comment]
We were looking at the issue and comparing the two options to handle the `delete`. One is to use the `ownerReferences` which could only work for kubeflow deployed through operator which has the `kfdef` object as the root owner reference and let the garbage collection do the cleanup. But this approach won't be able to handle the deployment through `kfctl` command line. The other one is to attach a common label to the top level components  defined in the kfdef yaml and the `delete` action will search all objects with the label and delete them. This should work for both CLI and operator installations. Any preference?

**Comment by animeshsingh** [comment]
Thanks @adrian555 

@jlewi @gabrielwen what's the plan for kfctl delete? Please see @adrian555 response above

**Comment by jlewi** [comment]
What namespaces are you talking about? 

It seems like there are 3 classes of namespaces

1. The namespace where the CR is created
1. The system namespaces created by kubeflow 
    * Primary namespace would be kubeflow where shared components run
    * istio-system and knative would also fall into this category
1. User namespaces 
    * These are profile controlled namespaces where users run notebooks, jobs, models etc...

It looks like the original bug report might have been talking about 1. 

Furthermore, it looks to me like the problem in the original bug report was that the same namespace was used for #1 and #2. 

Its not clear to me whether this is working as intended. I would probably say that the KFDef CR should not be created in the same namespace as the namespace into which the kubeflow control plane is deployed.

Should KFDef be a cluster scoped CR as opposed to namespace scoped?

A kubeflow installation consists of at least two namspaces
* The control namespace
* The namespce(s) in which KF is consumed.

The use case @animeshsingh has described which is install KF and restrict it to a subset of namespaces seems consistent with a cluster scoped resources that some how lists the namespaces  which it is allowed to use interact with.

**Comment by vpavlin** [comment]
Thanks for the detailed thoughts @jlewi 

> I would probably say that the KFDef CR should not be created in the same namespace as the namespace into which the kubeflow control plane is deployed.

Right now the Kubeflow is deployed to wherever the CR is. This seems like a correct behaviour consistent with many operators I have encountered - why do you think it is wrong? 

In case we agree it is wrong, we will need to add deployment namespace into the spec somehow so that kfctl and the operator can react to it .

If you believe Kubeflow should "own" the namespaces it deploys to (istio-system, kubeflow) that is a different story and it probably calls for the cluster wide resource.

At the same time I believe that there is a use case for having multiple KF instances deployed in a single cluster - which would mean we need the namespaced CR - what are your thoughts about this use case in general?

One thought for this - what if kfctl submitted the KFDef to the cluster (unless running as an operator, because that would be duplicate) - this way we could have owneReference for namespaces even while running with kfctl?

**Comment by animeshsingh** [comment]
thanks folks

@jlewi coming to the specific problem at hand - quickly either we fix it in a more generic way in kfctl delete (as mentioned by @adrian555  -attach a common label to the top level components defined in the kfdef yaml and the delete action will search all objects with the label and delete them.), or we use the `ownerReferences` with Operator (would prefer that)

**Comment by vpavlin** [comment]
My 2c - using the label and delete from kfctl sounds like a hack and I would definitely prefer the use of `ownerReferences` since that does not require kfctl to reimplement the clean up logic already present in Kubernetes.

@animeshsingh  what do you think about my proposal to upload the KFDef object to the cluster even when deploying using `kfctl`?

**Comment by animeshsingh** [comment]
thanks @vpavlin - " upload the KFDef object to the cluster even when deploying using kfctl" - sounds good, there are other open issues on making kfctl client have more intelligence (aka behave like an operator), and we can bundle this with those. 

@adrian555 can you open an issue vis a vis @vpavlin request, and then move ahead and implement the current delete functionality using ownerReference.

**Comment by animeshsingh** [comment]
@vpavlin @nakfour this was addressed through this PR, so wondering if its just a matter of picking up in ODH

**Comment by nakfour** [comment]
@animeshsingh I tested today with master branch, and it still deletes the namespace. 
Here are the steps I took to reproduce 
1. build/install operator from master branch
2. oc new-project opendatahub
3. oc create -f  -f https://raw.githubusercontent.com/opendatahub-io/odh-manifests/master/kfdef/kfctl_openshift.yaml
4. wait, then delete oc delete -f  https://raw.githubusercontent.com/opendatahub-io/odh-manifests/master/kfdef/kfctl_openshift.yaml
You will notice the project opendatahub deleted.
/cc @vpavlin

**Comment by adrian555** [comment]
@nakfour just want to confirm if you updated deploy/operator.yaml to use the image built from master branch for the operator?

**Comment by adrian555** [comment]
The test I just did went well and left the `opendatahub` namespace around. After the delete, there are still following resources left 

```
[root@kube43-inf kfctl]# oc get pods
NAME                                         READY   STATUS    RESTARTS   AGE
grafana-operator-7bd878c686-rhswn            1/1     Running   0          8m49s
prometheus-operator-84bbdb5f5b-2qccb         1/1     Running   0          8m34s
seldon-controller-manager-5958f65db8-jkbxb   1/1     Running   0          9m7s
[root@kube43-inf kfctl]# oc get deployment
NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
grafana-operator            1/1     1            1           8m54s
prometheus-operator         1/1     1            1           8m39s
seldon-controller-manager   1/1     1            1           9m12s```

These three are created by the OLM I assume since the OpenDataHub manifest just creates subscriptions to the operator. The subscriptions are deleted as their owner is the kfdef. But these operators are not owned by kfdef so they are not uninstalled.

**Comment by adrian555** [comment]
@animeshsingh yes, that is the plan we discussed yesterday.

**Comment by nakfour** [comment]
@adrian555 yes I built the operator and replaced the image. Yes these are subscription to operators that will linger, this is logic in OLM that assumes someone else might be using the operators and that why OLM keeps them. How did you delete the kfdef?

**Comment by adrian555** [comment]
these are the commands I ran

```
oc create -f deploy/crds/kfdef.apps.kubeflow.org_kfdefs_crd.yaml
oc create -f deploy/service_account.yaml -n openshift-operators
oc create clusterrolebinding kubeflow-operator --clusterrole cluster-admin --serviceaccount=openshift-operators:kubeflow-operator
oc create -f deploy/operator.yaml -n openshift-operators
oc new-project opendatahub
oc create -f https://raw.githubusercontent.com/opendatahub-io/odh-manifests/master/kfdef/kfctl_openshift.yaml
```
followed by (after the odh is up)
```
oc delete -f https://raw.githubusercontent.com/opendatahub-io/odh-manifests/master/kfdef/kfctl_openshift.yaml
```

**Comment by vpavlin** [comment]
I have rebuilt from master today and followed the same process and the namespace stayed there after the kfdef has been deleted, so it worked for me as expected

**Comment by animeshsingh** [comment]
@nakfour is this still an issue building from master and replacing the image for you?

**Comment by vpavlin** [comment]
To make sure anyone seeing this issue is not confused whether it is still issue or not - we've verified that this works fine, thanks @animeshsingh

**Comment by pinglin** [comment]
It seems that during the Kubeflow teardown, the kfctl operator still deletes `istio-system` even if `istio-crds` and `istio-install` in the kustomize YAML are taken off. I've checked the namespace of `istio-system` and its indeed bound with the kubeflow `ownerReferences`. So the delete makes sense.

However, the problem is that we have a pre-installed `istio-system` namespace, and we would like to keep it running and decouple it from the kubeflow lifecycle.

Is there a workaround for this?

**Comment by vpavlin** [comment]
@pinglin That's interesting - just to confirm I understand correctly - the `ownerReferences` are added even if istio componetns are not part of the KFDef?

**Comment by pinglin** [comment]
Yes, that is correct. 

Specifically, I deployed the Kubeflow suite with the [KFDef - kfctl_istio_dex.v1.0.2](https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_istio_dex.v1.0.2.yaml) by removing the [section](https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_istio_dex.v1.0.2.yaml#L19-L34) as instructed in the official [doc](https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/#notes-on-the-configuration-file).

The kfctl operator was installed as 
```
git clone https://github.com/kubeflow/kfctl.git && cd kfctl || exit
cd deploy || exit
kustomize edit set namespace kubeflow

# Only deploy this if the k8s cluster is 1.15+ and has resource quota support
kustomize edit add resource ../kustomize/include/quota
kustomize build | kubectl -n kubeflow apply -f -
```
And the status of namespace `istio-system` after the deployment was as follows:
```
$ kubectl get ns istio-system -n istio-system -o yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"kustomize.component":"cluster-local-gateway"
},"name":"istio-system","ownerReferences":[{"apiVersion":"kfdef.apps.kubeflow.org/v1","blockOwnerDeletion":true,"controller":tru
e,"kind":"KfDef","name":"kubeflow","uid":"5a8e62da-4c42-4126-b40e-57e400d78acd"}]}}
  creationTimestamp: "2020-05-28T21:32:26Z"
  labels:
    kustomize.component: cluster-local-gateway
  name: istio-system
  ownerReferences:
  - apiVersion: kfdef.apps.kubeflow.org/v1
    blockOwnerDeletion: true
    controller: true
    kind: KfDef
    name: kubeflow
    uid: 5a8e62da-4c42-4126-b40e-57e400d78acd
  resourceVersion: "25642065"
  selfLink: /api/v1/namespaces/istio-system
  uid: b14eef41-56d2-43af-84ee-28b32f0b880d
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

**Comment by adrian555** [comment]
Apparently the manifests for `cluster-local-gateway` application also contains a [`namespace.yaml`](https://github.com/kubeflow/manifests/blob/master/istio-1-3-1/cluster-local-gateway-1-3-1/base/namespace.yaml) pointing to `istio-system`. The `ownerReferences` is added to this yaml. So even though the `istio-crds` and `istio-install` applications are not in the kfdef CR, the `istio-system` namespace configuration still gets updated.

The easier approach is to remove the `namespace.yaml` from the manifests repo. May also need to think how to fix such scenario in operator code.
