### ISSUE TITLE
kfctl implements State Store

### ISSUE THREAD

**Issue by swiftdiaries** [kubeflow/kfctl#250]
Related issue: https://github.com/kubeflow/kfctl/issues/214

The kfctl-operator provides a built-in way to handle reconciliation of KF clusters by using the etcd state store (built-in with k8s). But this means that you need a k8s cluster.

For non-k8s based KF deployments; kfctl and kfctlServer; there is a need for implementing reconciliation.

One of the ways we can infer the state of the cluster (in order to reconcile) is to store the state of the cluster in an object store (generated configs and instrument the Status field in KFDef).

This allows us to do:
* periodic health checks 
* kick-off reconciliation when current state differs from stored state.

State Stores considered:
* GCS
* S3
* Minio
* Swiftstack
* Filesystem (for non-prod environments)

Reference:
This is already an established pattern being used in production with `kops`.
Kops has a k8s-style API similar to KFDef and uses a standardized storage interface to setup and communicate with the intended state store (GCS, S3).

I'm looking to explore this in the next couple of days. Opening this issue for feedback/suggestions/discussion.

/assign @swiftdiaries 

/cc @jlewi @gabrielwen @krishnadurai @yanniszark

**Comment by yanniszark** [comment]
Hi @swiftdiaries, this is very interesting, looking forward to your findings!
Some thoughts:
* Kubernetes controllers are asynchronous and rely on watching etcd for events. Is this a goal here? How will this be achieved with different data stores?
* What exactly will be stored inside the data store?
* S3-like stores also present the technical limitation of being eventually consistent, vs the filesystem or etcd that is consistent. This will probably affect the reconciliation process.

**Comment by animeshsingh** [comment]
thanks @swiftdiaries - looks good, but am not sure we want to create a split brain syndrome here. Why do we want to replicate something which operator + etcd combination is already doing? If anything, we can figure what else we can store in etcd, but use it as a master.  And for folks looking for operational characteristics, recommend using the master? Yes we need k8s, but anyone deploying kubeflow will have k8s?

**Comment by swiftdiaries** [comment]
Hey @animeshsingh 
Went through the operator code and issues, it'll probably be better to re-use all the work done there. 
Regarding the dependency on k8s, I was thinking more about deploying to multiple clusters like the Click2Deploy app currently does for GCP.
If an operator were to install Kubeflow on the same cluster then it's very useful. But if we want to deploy and manage Kubeflow for a fleet of clusters then how'd you do this with the operator?
I saw that the initial PR commented about this use-case, what is the current roadmap for the operator?

**Comment by jlewi** [comment]
There is a well defined pattern for using operators to control other infrastructure.

The pattern would be you have one K8s cluster that provides the control plane. This is where the "controller" (e.g. kfctl operator) would run. Each instance of the KFDef resource would then control a Kubeflow deployment that would (most likely) be running on a different cluster.

That said my oppinion on a KFDef/kfctl operator is changing. I think we are trending towards the direction where Kubeflow is a loose collection of applications and makes sense to manage each application semi-independently. I think the layer of abstraction that a high level operator like KFDef/kfctl introduces could be a barrier to platform operators from customizing and operating Kubeflow as needed.
