### ISSUE TITLE
kfctl build fails invalid config: version not supported, got v1

### ISSUE THREAD

**Issue by AndrewMcFarren** [kubeflow/kfctl#252]
Steps I used:

wget https://github.com/kubeflow/kfctl/releases/download/v1.0-rc.4/kfctl_v1.0-rc.3-1-g24b60e8_linux.tar.gz

tar -xvf kfctl_v1.0-rc.3-1-g24b60e8_linux.tar.gz

export CONFIG_URI="https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml"

export AWS_CLUSTER_NAME=kubeflow-demo
export KF_NAME=${AWS_CLUSTER_NAME}

export BASE_DIR=/home/ubuntu
export KF_DIR=${BASE_DIR}/${KF_NAME}

mkdir -p ${KF_DIR}
cd ${KF_DIR}
kfctl build -V -f ${CONFIG_URI}

**Error:  (kubeflow.error): Code 400 with message: Error creating KfApp from config file:  (kubeflow.error): Code 400 with message: invalid config: version not supported; supported versions: v1alpha1, v1beta1, got v1**

Environment:
kubectl version --short
Client Version: v1.17.3
Server Version: v1.14.9-eks-c0eccc

**Comment by plaffitte** [comment]
Hi @AndrewMcFarren I'm facing the exact same situation, would you mind sharing how you resolved the issue?

**Comment by AndrewMcFarren** [comment]
Haven't played with this in awhile, but as I recall I had to find kfctl installation/binary in my path and remove/delete it.  Then re-install it, and then it worked.

**Comment by Jeffwan** [comment]
Please always use the latest kfctl. Glad you figure it out
