### ISSUE TITLE
kfctl does not create IAM Roles for OIDC Identity Provider

### ISSUE THREAD

**Issue by Julianxo** [kubeflow/kfctl#255]
/kind bug

**What steps did you take and what happened:**
I followed this tutorial
https://www.kubeflow.org/docs/aws/iam-for-sa/

I added the line
`enablePodIamPolicy: true`
to my config under spec of the aws plugin.
I ran kfctl apply.
But the IAM roles are not created.

**What did you expect to happen:**
I would expect kfctl to create the two IAM roles kf-admin-${AWS_CLUSTER_NAME} and kf-user-${AWS_CLUSTER_NAME}.

**Environment:**
Kubeflow version: 1.0RC
kfctl version: (use kfctl version): kfctl v1.0-rc.3-1-g24b60e8
Kubernetes platform: (e.g. minikube): AWS EKS
Kubernetes version: (use kubectl version): Client 1.16, Server 1.14
OS (e.g. from /etc/os-release): macOS Mojave 10.14.6

**Comment by Jeffwan** [comment]
@Julianxo Sorry this changes has not been released yet. Syncing with release team to cut the release for this change.

**Comment by Julianxo** [comment]
@Jeffwan Ok. I was just confused because it is already in the documentation.
https://www.kubeflow.org/docs/aws/iam-for-sa/

**Comment by Jeffwan** [comment]
This has been available since v1.0.1. Sorry for the confusion. @Julianxo 

/close
