### ISSUE TITLE
Unit testing for all codes

### ISSUE THREAD

**Issue by gabrielwen** [kubeflow/kfctl#26]
Tracking to make sure test coverage looks good.

**Comment by gabrielwen** [comment]
looks like we don't run `go test` during presubmits.

**Comment by gabrielwen** [comment]
this is for kfctl repo, not kubeflow.

**Comment by jtfogarty** [comment]
@gabrielwen I'm looking to contribute, how can I help

**Comment by gabrielwen** [comment]
@jtfogarty 
Hi Jeff,

Thanks for be willing to contribute!  We could definitely someone for the test coverage.  I think a good start would be taking a look at [kfapp](https://github.com/kubeflow/kfctl/tree/master/pkg/kfapp) and pick up sub-directories that you think test coverage can be improved.  Let me know if you need more info or you'd like to contribute to other aspects!

Thanks,

**Comment by gabrielwen** [comment]
@jtfogarty 

We could definitely use more test coverage for both [coordinator](https://github.com/kubeflow/kfctl/blob/master/pkg/kfapp/coordinator/coordinator.go) and [kustomize](https://github.com/kubeflow/kfctl/blob/master/pkg/kfapp/kustomize/kustomize.go).  Is this something you would be interested?

**Comment by jlewi** [comment]
I think we can close this out issue for kfctl when we have

1. Some unittests for kfctl
1. Unittests are being run as part of CI/CD

We have lots of unittests; e.g.
https://github.com/kubeflow/kfctl/blob/master/pkg/utils/k8utils_test.go

The test grid shows these unittest are being executed
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-periodic-kfctl

So I'm marking this as fixed.
