### ISSUE TITLE
Trying to recreate in different GCP zone - fails with store creation

### ISSUE THREAD

**Issue by chajath** [kubeflow/kfctl#278]
I've realized GCP deployment can't complete in us-east1-b due to the lack of GPU instance support (might be good to document this!) and was trying to update the zone setting in the config and do `kfctl apply` again, I'm stuck in the following errors:

```
ERRO[0011] Updating search-kubeflow-storage error: &{Code:NO_METHOD_TO_UPDATE_FIELD Location: Message:No method found to update field 'zone' on resource 'search-kubeflow-storage-metadata-store' of type 'compute.v1.disk'. The resource may need to be recreated with the new field. ForceSendFields:[] NullFields:[]}  filename="gcp/gcp.go:386"

ERRO[0011] Updating search-kubeflow-storage error: &{Code:NO_METHOD_TO_UPDATE_FIELD Location: Message:No method found to update field 'type' on resource 'search-kubeflow-storage-artifact-store' of type 'compute.v1.disk'. The resource may need to be recreated with the new field. ForceSendFields:[] NullFields:[]}  filename="gcp/gcp.go:386"
```

I've went in to GCP console and manually deleted these disks, but that didn't solve the problem. Any way I can manually delete and recreate those storage definitions?

**Comment by jlewi** [comment]
With 1.1 we are switching to using GCP blueprints
https://github.com/kubeflow/gcp-blueprints/tree/master/kubeflow

Which uses Cloud Config Connector to describe and provision your GKE clusters. You can use tools like kustomize and kpt to config the YAML describing your clusters as necessary.
