### ISSUE TITLE
kfctl set-image-name command not found anymore in latest kfctl 1.0.1 bin

### ISSUE THREAD

**Issue by chethanmahadevaiah** [kubeflow/kfctl#280]
kfctl set-image-name command not found anymore in latest kfctl 1.0.1 bin.
Tried updating the image repos to the custom repository using kfctl set-image-name command, however error thrown when executed.
STDOUT of kfctl set-image-name unknown command "set-image-name" for "kfctl"

This functionality was working fine with few issue in 0.7.1 kfctl version.

bin used: kfctl_v1.0.1-0-gf3edb9b_linux.tar.gz 

Could some one please check if this is expected/removed from kfctl. Should i fall back to kustomise bin??

**Comment by yanniszark** [comment]
@chethanmahadevaiah I believe it was feature-flagged behind the alpha command.
So `kfctl alpha set-image-name`

**Comment by chethanmahadevaiah** [comment]
Thank you @yanniszark, it must work now then.

**Comment by yanniszark** [comment]
@chethanmahadevaiah closing then
We have an open issue for explaining the usage of kfctl set-image-name, hopefully someone will get this soon: https://github.com/kubeflow/website/issues/1539
/close
