### ISSUE TITLE
kfctl: support one command to bootstrap KCC controller

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kfctl#281]
With current kfctl logics, we can have a new command to bootstrap KCC controller environment on GCP.
Specifically the command should:
* create a GKE cluster
* create a GCP service account for KCC with necessary permissions
* deploy KCC controller inside new GKE cluster, with workload identity of the new service account

KCC instructions: https://cloud.google.com/config-connector/docs/how-to/getting-started

**Comment by yanniszark** [comment]
@kunmingg this seems more like a manifests issue.
Isn't the config controller similar to a k8s controller that people can install through yaml?

**Comment by kunmingg** [comment]
@yanniszark 
Description updated. The new cmd will primarily focus on creating cluster and grant permission for KCC controller.

**Comment by jlewi** [comment]
@kunmingg Lets discuss to figure out the priority.

**Comment by jlewi** [comment]
anthoscli should now support the full set of KCC resources so not sure we need this anymore.

**Comment by PatrickXYS** [comment]
Since GCP has migrated out of kfctl and use gcp-blueprint instead, close the issue

/close
