### ISSUE TITLE
Improve the kfctl delete algorithm

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kfctl#293]
I'm opening this issue to explain what kfctl delete does right now, the problems users have bumped into and how we can make it better.

**What `kfctl delete` does right now:**
* Delete some predetermined global resources with a LabelSelector:
    * CRDs, ClusterRoleBindings, ClusterRoles
* Delete Kubeflow namespace

**Issues with current approach:**
* Relies on correct labels existing on Kubeflow resources.
* Asymmetric: resources are created with kustomize build, but are deleted with a LabelSelector and by deleting namespaces.
* Misses other namespaces of Kubeflow:
    * auth namespace for dex
    * knative namespace
    * istio namespace
    * cert-manager namespace
* Misses global resources:
    * cert-manager apiservice
* Many issues about buggy behaviour: https://github.com/kubeflow/kfctl/issues/56, https://github.com/kubeflow/kubeflow/issues/4807, https://github.com/kubeflow/kubeflow/issues/3767, https://github.com/kubeflow/kubeflow/issues/4486, https://github.com/kubeflow/kubeflow/issues/4496

**Proposed solution:**
We could patch the current code with more ways to find what's missing,
however I believe the best and most sustainable way to ensure delete works correctly is to follow a symmetric model.

Just like how in our dev workflows we do `kubectl apply -f` and `kubectl delete -f` which are symmetrical, `kfctl` should also follow the same symmetrical model.
I'm hoping that once we can agree on a design, development shouldn't be too hard.

cc @jlewi @vaskoj @DiscordianFish @gabrielwen

**Comment by jlewi** [comment]
@yanniszark are you proposing that  `kfctl delete` is just sugar for `kustomize build -f | kubectl delete -`? 

Should we even have a `kfctl delete` command? At this point maybe we should keep it only for backwards compatibility. However, assuming `kfctl delete` is just a wrapper for `kustomize build -f | kubectal delete -` then maybe it would be better not to have `kfctl delete` as its an invitation for people to request/features different from `kubectl delete`.

The one reason I can think we might need it is to provide sugar for looping over all the kustomize packages and issuing a 

```
kustomize build -f | kubectl delete -
```

For each of them.

**Comment by yanniszark** [comment]
> @yanniszark are you proposing that kfctl delete is just sugar for kustomize build -f | kubectl delete -?

Yeap! In the same way that apply is a wrapper for kustomize build -f | kubectl apply -f -
The kfctl delete command is to wrap the loop over the kustomize packages in the order defined by KfDef.
What do you think?
Implementation should be fairly straightforward:

1. Build kustomize folder if necessary
2. For every application in reverse KfDef order, do an equivalent of kustomize build | kubectl delete -f -

**Comment by discordianfish** [comment]
> @yanniszark are you proposing that kfctl delete is just sugar for kustomize build -f | kubectl delete -?

This won't work for resources that are removed from kustomize though, right?

**Comment by yanniszark** [comment]
@discordianfish can you elaborate a bit more on your point?
I don't think I understand it. An example would also be very helpful.

**Comment by jlewi** [comment]
@yanniszark +1

**Comment by discordianfish** [comment]
@yanniszark If kustomize generates a resource 'foo', we update the manifests so that it won't generate the source 'foo', a `kustomize build -f | kubectl delete` wouldn't delete it.

But now that I think about it, that's not a problem. We just need to make sure that the delete runs with the same manifests as the create/apply did. IMO there should be some sort of safe guard to ensure that. For example, we could store a checksum or git sha from the manifests somewhere and make sure that's the same when delete runs.

**Comment by Jeffwan** [comment]
This would be helpful. in AWS implementation, we explicitly list those dependencies and clean them up during the `delete`. This is not that elegant and we definitely need better design on this. 

https://github.com/kubeflow/kfctl/blob/ff26056240c533f37bf8768902886ac454fbf5bf/pkg/kfapp/aws/aws.go#L102-L135

**Comment by jlewi** [comment]
It sounds like the problem @discordianfish fish is describing is pruning. This comes up in upgrades.

See kfctl/issues#304 for some thoughts on pruning.

> But now that I think about it, that's not a problem. We just need to make sure that the delete runs with the same manifests as the create/apply did. IMO there should be some sort of safe guard to ensure that. For example, we could store a checksum or git sha from the manifests somewhere and make sure that's the same when delete runs.

In general I think we should get out of the business of applying/deleting manifests. We should follow a shift left philosphy and defer that functionality to tools that can handle that better than we can. Ideally, I think we should be headed in the direction of

```
kfctl build -f my_kfdef.yaml | kustomize build -f | kubectl apply -f
```

I think the primary function of kfctl should be generating a set of kustomize manifests customized for the user. (Even this functionality is being subsumed by other tools like kpt).

In terms of build/apply/delete the primary functionality I see kfctl providing is iterating over a set of a directories and issuing build/apply/delete commands. Ideally this functionality would also be upstreamed into tools like kustomize or kpt.

**Comment by yanniszark** [comment]
@jlewi I'd love to see us depend on specialized tools in the future as well!
Also, thanks for shedding some light on pruning.
I have made a PR to address this issue: #309 
After it goes in, we should have a reliable way of deleting a Kubeflow cluster until we can shift this functionality to better tools.
