### ISSUE TITLE
e2e test for kubeflow on KCC

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kfctl#294]
We need to setup e2e test to cover kubeflow on KCC:
* setup long running KCC controller in kubeflow test project
* during every e2e test run:  
  * create CNRM resource in KCC controller
  * deploy kubeflow manifests
  * run all sub tests
  * delete CNRM resources

**Comment by jlewi** [comment]
@kunmingg I'm thinking we should just setup auto-deploy to periodically deploy a new Kubeflow instance and run the tests against that.

This is the dashboard that runs the examples:
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-periodic-examples

**Comment by jlewi** [comment]
Duplicate of kubeflow/gcp-blueprints#42
