### ISSUE TITLE
istio injection in Kubeflow namespace breaks KF 1.0 configs

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kfctl#296]
#131 changed kfctl to set a label on the kubeflow namespace to turn on istio sidecar injection in the kubeflow namespace.

This change is not backwards compatible; i.e using an updated kfctl with the existing KFDef 1.0 manifests would cause Kubeflow 1.0 to stop working because kubeflow 1.0 is not comaptible with istio side car injection in the kubeflow namespace.

This is causing the tests on the kubeflow/manifests 1.0 branch to fail because they are testing with kfctl from master.

Proposed course of action:

1. Rollback #131 
1. Figure out a way to selectively enable istio side car injection only for Kubeflow configs >= 1.1

/assign @Bobgy

**Comment by Bobgy** [comment]
Makes sense to me.

So we can guard the behavior of enabling istio injection in kfctl behind a config value in KfDef?
Who's the best person I should talk to? Should I try to contribute this one?

**Comment by jlewi** [comment]
@Bobgy Yeah I think it would be great if you could pick this up. I think the difficulty will be deciding on a good pattern for implementing this.

Here are some of the options I can think of.

1. Adding an explicit field to KFDef for this
1. Adding logic based on the version/url of the manifests to decide whether its sufficiently high enough version to turn on istio
1. Applying KFDef's labels to the Kubeflow namespace
1. Adding a KFDef annotation
1. Create a new kustomize package that defines the namespace objects with associated labels

I don't think #1 is a good approach. In general, I want to remove logic and KFDef and kfctl and move kfctl in the direction of being dumb, syntactic sugar around kustomize. So I think this would be a step in the wrong direction.

#2 seems brittle.

For #3 I'm not sure how we would achieve consistent semantics.  In particular KF is potentially creating multiple namespaces (e.g. namespace for kubeflow components, istio namespace, knative, etc....).  I don't think its true that we would want to set istio side car injection in all those namespaces uniformly. So applying the labels to all the namespaces wouldn't work and I don't like the idea of hardcoding special treatment for certain namespaces.

#4 This is probably the obvious quick fix but it feels like a bit of a hack.

#5 I think I like this approach the best. Moving the namespaces we want created into YAML files as opposed to defining them in code seems consistent with the overall direction we want to move in. It also makes it really easy for users to customize. However, there might be some problems I'm not anticipating.

@yanniszark @johnugeorge @animeshsingh WDYT?

**Comment by Bobgy** [comment]
Thanks for the thorough evaluation of tradeoffs. I totally agree `#5` is the best from my point of view (that was actually my initial attempt before forking kfctl, but I figured out it didn't work because namespace need to be created at the beginning, patching additional label during resource creation may cause problems).

But maybe we can have a way to let kfctl apply namespace from a resource file instead, will think about this.

**Comment by jlewi** [comment]
> namespace need to be created at the beginning, patching additional label during resource creation may cause problems, e.g. deployments created before the istio injection label is added will not get sidecars

If the order of operations is 

* Create istio namespace with labels
* Create istio resources
* Create kubeflow namespace with labels
* Create kubeflow resources

So kubeflow resources are created after istio and if the namespace is labeled with istio side car injection then istio would already be running and side cars will be injected

**Comment by Bobgy** [comment]
@jlewi I agree the ordering looks logical, but that requires a sequential dependency between components and extra logic in kfctl (adding labels in namespaces etc.). I think it's hard to express that in KfDef if we want to go with #5

Alternatively, I'm thinking if we can extend the constraint of separation between cluster-scoped resources and namespace resources.

KfDef can have a set of components, some marked as cluster-scoped components.

When kfctl applies manifest, it will apply cluster-scoped components as the first thing after cluster is ready.
So the ordering is like:
* apply cluster-scoped resources
* kfctl existing magic that adds a bunch of stuff
* apply namespace-scoped resources (like all existing components)

So we can put namespace resources into the cluster-scoped resources, extra labels/annotations there won't conflict with kfctl's existing logic and we don't need to let istio components deployed before some kfctl's existing logic.

These are my initial rough ideas (haven't tried with a demo). What do you think?

**Comment by jlewi** [comment]
The general direction we want to move is not putting more custom rollout logic into kfctl. We'd like to rely on existing tools to figure out the proper way to sequence objects. For example, I think kustomize, kpt, and ACM are already smart enough to deploy CRDs before creating instances of the resources.

>  I agree the ordering looks logical, but that requires a sequential dependency between components and extra logic in kfctl (adding labels in namespaces etc.).

I think what I'm proposing would eliminate custom logic in manifests. We would basically define "kustomize" packages 1 per namespace for each namespace we wanted to create. The labels would then be defined in the manifest as opposed to kfctl go code.

KFDef uses a list for the applications(kustomize manifests) so we just need to list the packages in the appropriate order.

As an example on GCP we want to support GitOps using [ACM](https://cloud.google.com/anthos-config-management/docs/concepts/repo#structure_of_the_repo). ACM is

1. Oppinionated about repo structure
1. Only works with hydrated manifests (hydrated= fully rendered YAML)
1. Supports creation of namespaces and objects within those namespaces.

So using ACM the process would look something like

```
kfctl build ...  | <hydrate by running kustomize build> | <layout manifests according to ACM>
```

So apply ordering logic is handled by ACM.

So I think pulling the namespace definitions out of go code and putting them in YAML is a step in the right direction.

**Comment by Bobgy** [comment]
> The general direction we want to move is not putting more custom rollout logic into kfctl.

Totally agree on the direction. If we remove all the kfctl custom rollout logic, we can use namespace resources right away, without parameters in kfdef about apply order.

I'm more concerned with how we can merge back the istio injection label before that, especially when kfctl is in the progress of removing the custom logic, how can namespace resources be applied at the right timing? Can we add hack like parsing the resources and apply namespaces first, before we remove all other kfctl custom rollout logic.

I don't think I will have bandwidth (and the knowledge) to contribute to refactoring kfctl.

**Comment by Bobgy** [comment]
TODO for me:
I can test using kfctl-v1 with namespace resource, report what was the blocking issue back here.

**Comment by jlewi** [comment]
@Bobgy Sounds good. If you look at the logic;
https://github.com/kubeflow/kfctl/blob/660fae1432982099a9b630b34181de8418c42c20/pkg/kfapp/kustomize/kustomize.go#L176

Applications are applied in the order they appear in KfDef.Application. So we just need to put the namespace applications at the right position in KFDef.Applications to control ordering.

**Comment by jlewi** [comment]
@Bobgy I've been experimenting with installing Kubeflow with kpt and kcc.
Here's my experiment
https://github.com/jlewi/kf-templates-gcp/blob/f3a4694c4daf2664230c6fc093ada744f65244cd/kubeflow/Makefile#L63

As you can see there I have a kustomize package which defines the namespaces. So any labels could just be added to the respective namespace resource.

That package is applied before applying anything that depends on those namespaces.

**Comment by Bobgy** [comment]
> @Bobgy I've been experimenting with installing Kubeflow with kpt and kcc.
> Here's my experiment
> https://github.com/jlewi/kf-templates-gcp/blob/f3a4694c4daf2664230c6fc093ada744f65244cd/kubeflow/Makefile#L63
> 
> As you can see there I have a kustomize package which defines the namespaces. So any labels could just be added to the respective namespace resource.
> 
> That package is applied before applying anything that depends on those namespaces.

Thanks @jlewi! That looks great! Do we plan to release KF 1.1 gcp env with kpt and kcc approach?

Sorry I've been busy with some other stuff, didn't have time to look into this yet.

**Comment by jlewi** [comment]
@Bobgy yes I think for GCP and KF 1.1 kpt and kcc will be the recommended approach.

**Comment by Bobgy** [comment]
@jlewi I tried using kfctl 1.0.2 with an additional application containing just the namespace at the beginning of kfdef yaml file. Looks like it successfully patched kubeflow namespace to enable istio label.

Then let's go with this approach, sounds good?

**Comment by jlewi** [comment]
LGTM

**Comment by Bobgy** [comment]
/close
I think we can close this and keep tracking in https://github.com/kubeflow/kubeflow/issues/3866
