### ISSUE TITLE
kfctl apply fails in GCP

### ISSUE THREAD

**Issue by jtfogarty** [kubeflow/kfctl#330]
I'm testing [#1947]( https://github.com/kubeflow/website/issues/1947)  in my corporate GCP and am running into this error;
```
INFO[0000] Creating deployment kf-jtf-01-storage         filename="gcp/gcp.go:462"
Error: failed to apply:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflow.error): Code 500 with message: gcp apply could not update deployment manager Error could not update storage-kubeflow.yaml; Insert deployment error: googleapi: Error 403: Request had insufficient authentication scopes.
More details:
Reason: insufficientPermissions, Message: Insufficient Permission
```
The first time I executed this, I got an error about there not being a default network, which is true.  I found the below in `storage.jinja`
```
privateNetwork: projects/{{ env['project'] }}/global/networks/default
```
I updated `storage.jinja` and hardcoded my network name

The service account has Owner and Editor roles

**Comment by jtfogarty** [comment]
@jlewi has this been tested without a default network?
Thanks

**Comment by jtfogarty** [comment]
gcloud --project=${PROJECT} deployment-manager deployments list returns 0 items

**Comment by jlewi** [comment]
@jtfogarty Are you executing this from a GCE VM? The error

```
Error: failed to apply:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflow.error): Code 500 with message: gcp apply could not update deployment manager Error could not update storage-kubeflow.yaml; Insert deployment error: googleapi: Error 403: Request had insufficient authentication scopes.
```

Like indicates you are using the GCE VM's service account to authenticate to GCP services and that's not working because it doesn't have sufficient scopes.

You can run 

```
gcloud auth list
```

To see which account is activated.

You can then run the following commands

```
gcloud auth login
gcloud auth application-default login
```

You need to run both in order to authorize kfctl to use your credentials.

**Comment by jtfogarty** [comment]
Yes that was the fix, thanks

**Comment by Geoyi** [comment]
I got the same error, though by running what @jlewi recommended did not help to solve the issue.
