### ISSUE TITLE
can't run kfctl inside kfctl docker image  - kfctl not found

### ISSUE THREAD

**Issue by micemuni** [kubeflow/kfctl#333]
Hello,

I used https://github.com/kubeflow/kfctl/tree/v1.0.2 to build kfctl as docker image, and running that image with CMD "kfctl apply -V -f ${CONFIG_FILE}" but it's throwing error. 

I followed the step https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/ and passing ENV value as export cmd 

I used sleep cmd to check Inside kfctl docker image :
```
root@ip-XXXX:/home/ubuntu/cloud-devops-us1# docker exec -it 898ab704e0e4 sh
/opt/kubeflow # ls
kfctl_aws.yaml
/opt/kubeflow # kfctl
sh: kfctl: not found

``` 
ERROR & Docker run cmd:
```
root@ip-XXXX:/home/ubuntu/cloud-devops-us1# docker run -d -e "PATH=$PATH:/usr/local/bin/" -e "CONFIG_URI=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.2.yaml" -e "AWS_CLUSTER_NAME=cloud-devops-us1" -e "KF_NAME=aip-cloud-devops-us1" -e "BASE_DIR=/opt/kubeflow/" -e "KF_DIR=/opt/kubeflow/" -e "CONFIG_FILE=/opt/kubeflow/kfctl_aws.yaml" --name tetks8 --mount type=bind,source=$(pwd)/kfctl_aws.yaml,target=/opt/kubeflow/kfctl_aws.yaml 0230d59fc584 "/usr/local/bin/kfctl apply -V -f /opt/kubeflow/kfctl_aws.yaml"

30ee74d2213a9fb12a9d7e35abfc92bb387a766ffe36409e22533f24ab9a096f

docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/usr/local/bin/kfctl apply -V -f /opt/kubeflow/kfctl_aws.yaml\": stat /usr/local/bin/kfctl apply -V -f /opt/kubeflow/kfctl_aws.yaml: no such file or directory": unknown.
``` 

Inside kfctl docker image 
``` 
/opt/kubeflow # ls /usr/local/bin
kfctl
/opt/kubeflow # /usr/local/bin/kfctl
sh: /usr/local/bin/kfctl: not found 
```

I suspect that kfctl CLI is not working,  https://github.com/kubeflow/kfctl/blob/v1.0.2/Dockerfile  
 Not sure is there any issue on Dockerfile build 
..?

**Comment by jbottum** [comment]
@micemuni Hi, thanks for entering this issue.   is this on EKS ?  what version of K8s are you using?

**Comment by micemuni** [comment]
@jbottum  I am using AWS eks 1.14 version.

**Comment by jlewi** [comment]
I don't think using the docker image is one of the officially supported ways of running kfctl. I would suggest trying one of the prebuilt binaries.

It looks like there might be an issue with the Docker image which you could try to debug and fix.

/cc @shawnzhu

**Comment by shawnzhu** [comment]
I can reproduce this problem by the following commands:

```SHELL
$ GOLANG_VERSION=1.14.3 make build-kfctl-container
$ docker run -it --rm --net host --entrypoint /bin/sh gcr.io/kubeflow-images-public/kfctl/builder:v1.0-rc.3-52-ge96de9d
/opt/kubeflow # kfctl version
/bin/sh: kfctl: not found
```

Notice that the `Dockerfile` of this repo is for building kfctl (via docker [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/)), not for redistributing nor running kfctl although it could work.

## Problem

☝️ steps should work. I'm interested in why it doesn't since the file does exist in given file system. I learned from the answer to the question [No such file when it exists](https://superuser.com/a/1176328):

> The shell will report an ambiguous "No such file or directory" for an executable when the shell cannot find a dependency for that executable.
The missing dependency is typically a required shared library or a dynamic loader.

Given the instructions here:

https://github.com/kubeflow/kfctl/blob/d1ba4b50d25931e75ba953ce2fb16ca91866127d/Dockerfile#L67-L74

It just copies single binary `kfctl` based on alpine v3.0.1 (w/o any shared library).

## Fix

I'm lucky and found a missing library `libc6-compat` (via `strings /usr/local/bin/kfctl | less`):

```
/opt/kubeflow # ls /lib64/ld-linux-x86-64.so.2
ls: /lib64/ld-linux-x86-64.so.2: No such file or directory
/opt/kubeflow # apk add --update libc6-compat
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
(1/2) Upgrading musl (1.1.22-r2 -> 1.1.22-r3)
(2/2) Installing libc6-compat (1.1.22-r3)
OK: 9 MiB in 20 packages
/opt/kubeflow # which kfctl
/usr/local/bin/kfctl
/opt/kubeflow # kfctl version
kfctl v1.0-rc.3-52-ge96de9d
```

PR is on the way

**Comment by shawnzhu** [comment]
> I don't think using the docker image is one of the officially supported ways of running kfctl. I would suggest trying one of the prebuilt binaries.

@jlewi 👍 Do you think it would be helpful by clarify this in doc like README? People like me will get used to run `docker build` when seeing `Dockerfile`. Or just rename it to `Dockerfile.build` to clarify its purpose.

**Comment by jlewi** [comment]
@shawnzhu I don't have an oppinion; whatever you and the other folks agree on sounds good to me.

/cc @MrXinWang

**Comment by micemuni** [comment]
Hi,
I have fixed with change --  CGO_ENABLED=0  in makefile & added ENTRYPOINT ["/usr/local/bin/kfctl"] in Dockerfile. 

makefile:
https://github.com/kubeflow/kfctl/blob/master/Makefile#L131
	GOOS=linux GOARCH=amd64 CGO_ENABLED=0 ${GO} build -gcflags '-N -l' -ldflags "-X main.VERSION=$(TAG)" -o bin/linux/kfctl cmd/kfctl/main.go

Then build / deploy, now kfctl is working inside kfctl image

**Comment by MrXinWang** [comment]
@micemuni @shawnzhu Added the `CGO_ENABLED=0` code to make binary use static compilation in this PR: #318, waiting for it to be merged now :))
