### ISSUE TITLE
kfctl - could not get platform aws Error Failed to create config file from /root/.kube/config 

### ISSUE THREAD

**Issue by micemuni** [kubeflow/kfctl#343]
Hello All,
I am using https://github.com/kubeflow/kfctl/tree/v1.0.2 kfctl docker image to deploy kubeflow https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/ in AWS cloud and used https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.2.yaml ( i have customized this yaml file )

Details FYI -- Using kubernetes_job resource to run "kfctl apply -V -f ${CONFIG_FILE}" in container at one time.  kfctl is creating kubernetes pods/services.., as per config from kfctl_aws.v1.0.2.yaml , this is triggering while container entrypoint.  

Blocker is -- kfctl is not using service account credentials ( attached IAM role has AWS resource creation permission ), that's why kubernetes API server saying system:ananymous forbidden error. kfctl is in inside container ( pods ) and kfctl is looking ~/.kube/config file in PODs itself, but it is not there.

How do we config that kfctl to use service account to create resource in AWS..??   OR
How to say to kfctl to use kubeconfig file credentials..??  OR
Is there any way to fix that error..?? 

Also i have added namespaces to rules that bind with sa, but still kube/config error from  pod/kubeflow,

error 1:- 
`
[root@a-3b7daj8kxugj2 ]# kubectl logs pod/kubeflow-8j6bp -n kubeflow

time="2020-05-28T11:34:20Z" level=info msg="No name specified in KfDef.Metadata.Name; defaulting to cloud-devops-us1 based on location of config file: /opt/kubeflow/cloud-devops-us1/kfctl_aws.yaml." filename="coordinator/coordinator.go:202"
time="2020-05-28T11:34:20Z" level=fatal msg="could not get platform aws Error Failed to create config file from /root/.kube/config **" filename="coordinator/coordinator.go:216"
`

error 2:- 
 `
module.aip_cloud.module.eks.random_pet.workers[1]: Refreshing state... [id=just-burro]
module.aip_cloud.module.eks.aws_autoscaling_group.workers[0]: Refreshing state... [id=cloud-devops-us1-worker-group-120200511075508666100000009]
module.aip_cloud.module.eks.aws_autoscaling_group.workers[1]: Refreshing state... [id=cloud-devops-us1-kiam-servers2020051107550866620000000a]
module.aip_cloud.module.kubeflow.kubernetes_namespace.kubeflow: Refreshing state... [id=kubeflow]

Error: namespaces "kubeflow" is forbidden: User "system:anonymous" cannot get resource "namespaces" in API group "" in the namespace "kubeflow"

`

**Comment by ivanjacobsec** [comment]
Hi
have you tried this?

aws eks --region _region-code_ update-kubeconfig --_name cluster_name_
Test your configuration.

kubectl get svc
[Source](https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html)

**Comment by micemuni** [comment]
Yes, tried no lcuk, Actually the kfctl is looking kubeconfig file in same path where we have kfctl_aws YAML file. 
But i am maintaining the kfctl files in different path like /opt/kubeflow/.

From my kubernetes infra code is running in diff path. So can we able to pass the kubeconfig file path to kfctl YAML..??

**Comment by ivanjacobsec** [comment]
sorry I am not able to help. I was not able to make i work eather

**Comment by micemuni** [comment]
Any one working on this issue OR workaround atleast. 

To automate the kubeflow deployment in kubernetes..?

As i said above, i used kubernetes_job resource tried to run kfctl apply cmd and suing kfctl_aws.v1.0.2.yaml, am getting error below ""could not get platform aws Error Failed to create config file from /root/.kube/config "" 

I have single kubeconfig file in cluster, but kfctl is looking that kubeconfig file inside kuubernetes PODs i guess, so that throwing error. 

Any idea..? workaround for this..?

**Comment by jbottum** [comment]
Hi @micemuni is this issue still open ?   Have you started to look at using GitOps for your deployments ?

**Comment by micemuni** [comment]
@jbottum  Actually i am trying to automate the kubeflow deployment in my existing Kubernetes platform, used manual steps to setup kubeflow
