### ISSUE TITLE
[Release 1.1] kfctl release

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kfctl#352]
Opening this issue to track releasing kfctl as part of 1.1.

* Ref: kubeflow/kubeflow#5022

* We will need to
   * Cut a release branch
   * Publish updated binaries for kfctl

We still need to find an owner

**Comment by crobby** [comment]
Per the discussion in:  https://github.com/kubeflow/kfctl/pull/338 I will take care of this for 1.1.

**Comment by jlewi** [comment]
@crobby Do you have the necessary permission to cut branches and do releases in GitHub?

Are we on track for 06/19 to do a branch cut and an RC?

**Comment by crobby** [comment]
@jlewi I doubt that I have permissions to cut branches and do releases.  This is my first rodeo, so any guidance you can give is greatly appreciated.

There are quite a few outstanding p0 items, but many of them seem to have been around for awhile, so I'm not sure how critical they might or might not be.  I will be going through them to see if there are any that I deem critical.

**Comment by crobby** [comment]
I have confirmed that I don't have permission for branches/releases.

**Comment by jlewi** [comment]
@crobby please take a look at the links in 
https://groups.google.com/forum/#!topic/kubeflow-discuss/pGflW6m9Xrg

To understand how github permissions are managed.

**Comment by crobby** [comment]
@jlewi (or anyone else who may know):  I have an rc.0 release up for the binaries.  I still need to see about adding some testing for the v1.1 branch, but one thing that isn't quite clear to me is how I get the operator image pushed to the desired location?  I see the Makefile has some targets that might help me with that, but they seem to do some "gcloud" commands.  Do I need an account of some sort for those things?  Any sort of special permissions?
Thanks

**Comment by jlewi** [comment]
@crobby I don't think we've been publishing docker images for kfctl. I think the docker images were largely intended for developers.

What does the release guide for kfctl say? Do we need to update the kubeflow website docs to point to the latest kfctl releases?

**Comment by crobby** [comment]
Ah, that would explain why I wasn't finding any docs about releasing the container images.  The guide only mentions the kfctl binaries, so I will go with that.
There is a section about "versioning the website", but that seems to be something that would be done outside of the specific kfctl release and as a part of the whole KF release since it impacts "everything".
Thanks again

**Comment by adrian555** [comment]
@crobby @jlewi @animeshsingh for the Kubeflow operator image, we will manually create one after the 1.1 release is out. In the longer term, we will seek the option to move the image to `gcr.io` and make it part of the release process. Thanks.

**Comment by jlewi** [comment]
@crobby Could you please open up a PR to update the release guide to explain that we aren't doing a docker image for kfctl?

Should we create a kfctl specific release guide in kubeflow/kfctl and then update the uber release guide to just point to it for kfctl?

The website is a separate process.

**Comment by krishnadurai** [comment]
@crobby  can we look to generate a binary for kfctl and post it here?

https://github.com/kubeflow/kubeflow/releases

**Comment by krishnadurai** [comment]
This can be tagged as v1.1.0-rc.0.

**Comment by jlewi** [comment]
@crobby any update?

**Comment by crobby** [comment]
@krishnadurai @jlewi Apologies, if it was also expected that I'd push the binaries up to:  https://github.com/kubeflow/kubeflow/releases  I did get rc-0 pushed up to https://github.com/kubeflow/kfctl/releases a couple weeks ago.

I do not have permissions to draft new releases in https://github.com/kubeflow/kubeflow/releases, so perhaps someone else can take care of that, otherwise, it will likely take me some time to track down the appropriate permissions to draft releases there.

**Comment by crobby** [comment]
> @krishnadurai @jlewi Apologies, if it was also expected that I'd push the binaries up to: https://github.com/kubeflow/kubeflow/releases I did get rc-0 pushed up to https://github.com/kubeflow/kfctl/releases a couple weeks ago.
> 
> I do not have permissions to draft new releases in https://github.com/kubeflow/kubeflow/releases, so perhaps someone else can take care of that, otherwise, it will likely take me some time to track down the appropriate permissions to draft releases there.

Best I can tell, I'd need to be added the release-team in order to be able to create releases at https://github.com/kubeflow/kubeflow/releases I'm not seeing a lower-perimssioned group that would achieve that.  Am I correct, or am I missing something?

**Comment by jlewi** [comment]
@crobby I think that's right as it exists today; although per the WG proposal I think we'd want to eventually create more narrowly scoped teams to admin the kubeflow/kubeflow repo.

That said; I think it makes sense to just publish the kfctl releases on the kfctl repo and make sure our docs point people there.

**Comment by crobby** [comment]
Any objections if I were to aim for cutting a new RC by the end of this week?

**Comment by crobby** [comment]
Ok, I have boxed-up rc1 for kfctl.  https://github.com/kubeflow/kfctl/releases/tag/v1.1-rc.1  I'll do some test driving.  Do let me know if you come across any issues.

**Comment by Jeffwan** [comment]
Seems this is done, we have 1.0.0 out.
