### ISSUE TITLE
kfctl 1.0.2 have vulnerability package

### ISSUE THREAD

**Issue by micemuni** [kubeflow/kfctl#395]
Hi Team,
I am using this kfctl git 1.0.2 branch and building as docker image to run kubeflow. When i scan that image vulnerability with kfctl below package 
musl-utils-1.1.22-r2 &  musl-1.1.22-r2, --> The fix is to use 1.1.22-r3 version.
thrift-0.12.0 ---> the fix is 0.13.0 

But i couldn't able to see where that version are mentioned in code..?  is this installed  as part of some other packages..? If yes, where it's..?

**Comment by Jeffwan** [comment]
@micemuni 

Thanks for reporting the issue. I think these are Alpine Linux packages. We probably need to upgrade base image version to patch the issues.

**Comment by jbottum** [comment]
@jtfogarty @krishnadurai Hey Jeff, Krishna, any comments on this ?

**Comment by jtfogarty** [comment]
@micemuni

What are you building as a docker image?  Can you post a link to your Dockerfile?

**Comment by micemuni** [comment]
@jtfogarty  I am using kubeflow kfctl git and trying to build kfctl binary to automate the kubeflow deployment using kubernetes resource, but no luck, so i deployed it via manual steps.
