### ISSUE TITLE
WG sponsorship for kfctl

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kfctl#399]
All projects need to find WG sponsorship or they will eventually be archived.

@adrian555 @animeshsingh @crobby @Jeffwan @vpavlin @yanniszark  What is the current thinking about a WG to own kfctl?

cc @Bobgy

**Comment by Jeffwan** [comment]
I think `wg-control-plane` is better. In yesterday community meeting, I think WG proposal is in progress

**Comment by PatrickXYS** [comment]
I think this issue is resolved by establishment of wg-deployment 

/close
