### ISSUE TITLE
Create pytest to verify that KSA and GSA are set correctly for workload identity manager

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kfctl#40]
In 0.7 we are enabling identity workload management on GKE.

As part of this when we create profiles we want to correctly bind GCP service accounts to KSAs.

kubeflow/kubeflow#3917 will update the profile controller to support this.

We also have code in kfctl to do this for the default namespace.

We should create a pytest that checks that the KSA and GSA for the newly created namespaces are correctly configured for workload identity.

We should then include this in a suitable E2E test for workload identity

**Comment by jlewi** [comment]
@kunmingg Did you add a test for this already?

**Comment by PatrickXYS** [comment]
Since GCP has migrated out of kfctl and use gcp-blueprint instead, close the issue

/close
