### ISSUE TITLE
MountVolume.SetUp failed for volume "webhook-tls-certs" : secret "webhook-server-tls" not found

### ISSUE THREAD

**Issue by zhangchunsheng** [kubeflow/kfctl#407]
kubeflow / cache-server log

```
MountVolume.SetUp failed for volume "webhook-tls-certs" : secret "webhook-server-tls" not found

Unable to attach or mount volumes: unmounted volumes=[webhook-tls-certs], unattached volumes=[kubeflow-pipelines-cache-token-xbbbk webhook-tls-certs istio-envoy sds-uds-path istio-token]: timed out waiting for the condition
```

**Comment by DavidSpek** [comment]
Would this by any chance be related to https://github.com/kubeflow/pipelines/issues/4505? What version of kubernetes are you using? How did you deploy kubeflow?

**Comment by jbottum** [comment]
Hi @zhangchunsheng, which platform are you running Kubeflow on i.e. AWS, GCP, on-prem ?

**Comment by zhangchunsheng** [comment]
> Hi @zhangchunsheng, which platform are you running Kubeflow on i.e. AWS, GCP, on-prem ?

Aliyun

**Comment by dale88** [comment]
I have the same issue.

**Comment by dale88** [comment]
I have solved this problem in my env.

I commented out everything in the cat /etc/resolv.conf.
