### ISSUE TITLE
Dumping generate invalid yaml

### ISSUE THREAD

**Issue by jtherin** [kubeflow/kfctl#412]
Using kfctl 1.1.0 and build from master

> kfctl build -d -f https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_k8s_istio.v1.1.0.yaml

generate an invalid yaml with empty line return instead of `---` between applications

Example:
```apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: kubeflow
    istio-injection: enabled
  name: kubeflow

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: kubeflow
    app.kubernetes.io/name: kubeflow
  name: applications.app.k8s.io
spec:
  group: app.k8s.io
  names:
    kind: Application
    plural: applications
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
...
```

(missing `---` between Namespace resource and CustomResourceDefinition resource)

**Comment by jbottum** [comment]
Hi @jtherin did you get this resolved ?  which platform (GCP, AWS, On-Prem) are you deploying on to ?

**Comment by jtherin** [comment]
I'm deploying on-prem. I pushed https://github.com/kubeflow/kfctl/pull/413 to fix it.
