### ISSUE TITLE
kfctl 1.2 release candidates

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/kfctl#421]
I am checking in if any features/improvement/bug fixes you plan to add into 1.2 release. I plan to cut release end of next week. 

@adrian555 @animeshsingh @PatrickXYS @mameshini 

WG-manifest will probably maintain a minimum distribution in the future. this is still in discussion in separate thread. 

For 1.2 release, we will rely on cloud providers to confirm their status. I think @PatrickXYS would also like to help test dex solution on AWS (we only have AWS resources for on-prem manifest).  

We will consider to bring presubmit test case back in kfctl. Please let me know if you have other things in mind. 
I will make a cleanup on existing PRs and recent issues

**Comment by Jeffwan** [comment]
I think we don't have blocking issues in kfctl.

**Comment by PatrickXYS** [comment]
I agree, we should be good to go with official 1.2 release on kfctl side

**Comment by Jeffwan** [comment]
I cut v1.2.0 https://github.com/kubeflow/kfctl/releases/tag/v1.2.0 and this can be closed
