### ISSUE TITLE
[Operator]Add operator manifests for 1.2 release

### ISSUE THREAD

**Issue by adrian555** [kubeflow/kfctl#422]
Tasks:
[ ] add 1.2.0 operator csv https://github.com/kubeflow/kfctl/tree/master/deploy/olm-catalog/kubeflow, make sure the proper kfdef CR is used in `alm-examples`
[ ] update current version https://github.com/kubeflow/kfctl/blob/master/deploy/olm-catalog/kubeflow/kubeflow.package.yaml
[ ] build operator image for 1.2.0 and update https://github.com/kubeflow/kfctl/blob/master/deploy/operator.yaml to use that image
[ ] update version # in https://github.com/kubeflow/kfctl/blob/master/cmd/manager/main.go#L35
[ ] update https://github.com/kubeflow/kfctl/blob/master/operator.md to include the instructions for 1.2.0
[ ] fix file name https://github.com/kubeflow/kfctl/blob/master/deploy/olm-catalog/kubeflow/1.1.0/kubeflow.v1.0.0.clusterserviceversion.yaml

**Comment by Jeffwan** [comment]
@adrian555 Any progress there? is this a blocking issue for kubeflow 1.2 release?

**Comment by evan-hataishi** [comment]
@Jeffwan I'll submit a PR for all this by the end of the week :)

**Comment by Jeffwan** [comment]
@evan-hataishi Do you need this to be in 1.2? We plan to cut the release this week.

**Comment by evan-hataishi** [comment]
@Tomcli What do you think?

**Comment by Tomcli** [comment]
@evan-hataishi can you update the version in https://github.com/kubeflow/kfctl/blob/master/cmd/manager/main.go#L35?

Everything else can be done after 1.2 release since olm yaml doesn't need to change the kfctl source code.
