### ISSUE TITLE
kfctl apply the same application multiple times if applications use the same name

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfctl#424]
When several applications using the same name in kfdef but pointing to different path, kfctl still applies the same application stack multiple times despite that all the applications are already packaged inside a common kustomize folder. Therefore, we need to update the kfctl apply logic to apply only once for each application name.

**Comment by moficodes** [comment]
I can investigate for a possible fix.

**Comment by Tomcli** [comment]
Problem also resolved in one of the latest commit, we need to cut a new release to address this issue.
/close
