### ISSUE TITLE
Cannot build from master with Dockerfile

### ISSUE THREAD

**Issue by wdhorton** [kubeflow/kfctl#43]
Steps:
clone `kfctl`
`cd kfctl`
`docker build .`

I get this error:
```
build github.com/kubeflow/kfctl/v3/cmd/kfctl: cannot load github.com/kubeflow/kubeflow/components/profile-controller/v2/pkg/apis/kubeflow/v1alpha1: cannot find module providing package github.com/kubeflow/kubeflow/components/profile-controller/v2/pkg/apis/kubeflow/v1alpha1
make: *** [Makefile:62: fmt] Error 1
```

I'm on commit `51703d5a77b371e4bc9f262f86caf549ae32a03b`

I suspect it might be because its downloading the v0.6.2 release of `kubeflow/kubeflow`?

```
go: finding github.com/kubeflow/kubeflow v0.6.2
go: downloading github.com/kubeflow/kubeflow v0.6.2
go: extracting github.com/kubeflow/kubeflow v0.6.2
```

**Comment by yanniszark** [comment]
@wdhorton this is still a mirror of kubeflow/kubeflow/bootstrap, which is the source of truth.
We should probably make a note of that in the README.
/cc @kkasravi

**Comment by PatrickXYS** [comment]
This is an old issue to be tracked. Let's not check too backward

/close
