### ISSUE TITLE
Homebrew kfctl

### ISSUE THREAD

**Issue by naveensrinivasan** [kubeflow/kfctl#454]
It would be nice to have a formula in [homebrew](https://brew.sh/) for `kfctl`

**Comment by adrianchia** [comment]
there was a problem building homebrew kfctl for 1.1.0 which was fixed in 1.2.0.rc0. I can submit the PR to homebrew when it is ready.

**Comment by naveensrinivasan** [comment]
I was able to get it working in `1.1.0` https://github.com/Homebrew/homebrew-core/pull/65230

**Comment by naveensrinivasan** [comment]
When the PR gets merged in. I will submit a PR to this repo for the documentation.

**Comment by naveensrinivasan** [comment]
The Upstream won't be able to accept the PR because we are compiling against `go` version `1.13` which is not maintained.

I tried compiling `kfctl` in `1.15` and there were `go vet` issues and couldn't compile it.


> So do you expect the upstream to fix this before coming with a brew formula?

> I expect upstream to not be a year behind in security updates. If there is no work being done to keep up to date I'd consider it abandoned and violating the rule:

https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff
> be maintained (i.e. the last release wasn’t ages ago, it works without patching on all supported macOS releases and has no outstanding, unpatched security vulnerabilities)

_Originally posted by @SMillerDev in https://github.com/Homebrew/homebrew-core/pull/65230#discussion_r528545331_

**Comment by jlewi** [comment]
Duplicate of #420
