### ISSUE TITLE
Create kf-user secret for backwards compatibility even if workload identity is enabled

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kfctl#46]
In 0.7.0 we are enabling workloadIdentity by default. Nonethless I think we should continue to create the secret kf-user in the Kubeflow namespaces and the profile namespaces.

e.g. in kfctl
https://github.com/kubeflow/kubeflow/blob/6739cd076d8dd9911ce40b44137a98b2a68efcca/bootstrap/pkg/kfapp/gcp/gcp.go#L1591

and in the profile controller

This is mainly to provide backwards compatibility with code that hasn't been updated yet to use workload identity.

I think we only need to create the kf-user secret and not the kf-admin  secrets.

User code should only be using kf-user not kf-admin.

**Comment by jlewi** [comment]
@kunmingg Does your PR from yesterday fix this issue?

**Comment by kunmingg** [comment]
Will be covered by https://github.com/kubeflow/kubeflow/pull/4309

**Comment by jlewi** [comment]
@kunmingg Can we write a simple test to help validate this?

For example could we just add a test function to [kf_is_ready](https://github.com/kubeflow/kubeflow/blob/master/testing/kfctl/kf_is_ready_test.py) that would verify the expected secrets are present in the expected namespaces?

**Comment by jlewi** [comment]
@kunmingg looks like we are just waiting on verification?

Looks like there is a test pending in #4350
