### ISSUE TITLE
Clean up stale branches

### ISSUE THREAD

**Issue by PatrickXYS** [kubeflow/kfctl#461]
We should clean up kubeflow/kfctl branches except for formal release branches, thus, I collected data points as below:

https://github.com/kubeflow/kfctl/branches/all

Otherwise, it's weird to end-user that other branches exist alongside the release branches

```
Bobgy-patch-1
richardsliu-patch-1
revert-131-enable_istio_injection_in_kf_ns
```

/cc @kubeflow/wg-deployment-leads

**Comment by Jeffwan** [comment]
+1

I help remove two. `richardsliu-patch-1` is a protected branch and I can not remove it. This has to be done by admin. write access is not enough. It's fine to leave one branch there
