### ISSUE TITLE
KFCTL FOR WINDOWS

### ISSUE THREAD

**Issue by sulabh2000** [kubeflow/kfctl#464]
Does Kubeflow provide kfctl for windows?
Cause I do not find here:-
https://github.com/kubeflow/kfctl/releases/tag/v1.1.0
If there is no release for windows then please suggest to me a way to install kfctl on windows.

**Comment by moficodes** [comment]
There is no plan currently for creating release for windows.

If you have access to wsl on windows you should be able to install kfctl in there. 

Another workaround could be using a docker image to have kfctl installed.

**Comment by sulabh2000** [comment]
ok thanks
