### ISSUE TITLE
[GCP] Workload identity not working; gke metadata server getting killed for failing liveness probe

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kfctl#48]
I deployed 0.7.0 which uses GCP workload identity.

Per the [instructions](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) I tried to verify workload identity was working by starting a container

```
kubectl run -it   --generator=run-pod/v1   --image google/cloud-sdk   --serviceaccount kf-admin   --namespace kubeflow   workload-identity-test-admin2
```

I then run

```
gcloud auth list
```

Which should print out my service but doesn't most of the time. It succeeds intermittently; otherwise it print out

```
gcloud auth list

No credentialed accounts.

To login, run:
  $ gcloud auth login `ACCOUNT`
```

The GKE metadata server is crash looping

```
kubectl -n kube-system get pods
NAME                                                             READY   STATUS             RESTARTS   AGE
gke-metadata-server-4pq8w                                        0/1     CrashLoopBackOff   516        26h
gke-metadata-server-4vmjh                                        0/1     CrashLoopBackOff   519        26h
```

Because they are failing their liveness probe

```
Events:
  Type     Reason     Age                     From                                                          Message
  ----     ------     ----                    ----                                                          -------
  Warning  Unhealthy  57m (x1500 over 26h)    kubelet, gke-jlewi-v07-001-jlewi-v07-001-cpu-p-dedaa1a1-480h  Liveness probe failed: Get http://10.142.15.216:54898/healthz: dial tcp 10.142.15.216:54898: connect: connection refused
  Normal   Started    12m (x515 over 26h)     kubelet, gke-jlewi-v07-001-jlewi-v07-001-cpu-p-dedaa1a1-480h  Started container gke-metadata-server
  Warning  BackOff    2m33s (x6096 over 26h)  kubelet, gke-jlewi-v07-001-jlewi-v07-001-cpu-p-dedaa1a1-480h  Back-off restarting failed container
```

Attaching more complete logs from stackdriver

[k8s_gke_logs.txt](https://github.com/kubeflow/kfctl/files/3715884/k8s_gke_logs.txt)

**Comment by jlewi** [comment]
This appears to be known issue with 1.14.6-gke.13
Current recommendation is to downgrade to 	1.14.6-gke.2

**Comment by jlewi** [comment]
Command to downgrade the master (you need to downgrade the master not the nodes).

```
gcloud container clusters upgrade [CLUSTER_NAME] --master --cluster-version=1.14.6-gke.2 --zone=[CLUSTER_ZONE]

```

**Comment by jlewi** [comment]
Filed kubeflow/manifests#508 to track unpinning.

**Comment by mvisonneau** [comment]
I still have this issue on `v1.14.8-gke.2` :(

```
~$ kubectl logs gke-metadata-server-swp4c
I1106 15:35:49.692938       1 main.go:78] gke-metadata-server revision 7b28a8ea4ac0da33ba983aab02168e36d3aa0680
I1106 15:35:49.693180       1 main.go:81] Creating CRI connection
F1106 15:35:49.693282       1 main.go:84] Failed to start CRI: unable to create cri: no socket found at ["unix:///var/run/dockershim.sock" "unix:///run/containerd/containerd.sock"]
```

**Comment by mareksuscak** [comment]
@mvisonneau exactly, this is affecting us as well, what's worse tho is that there's no longer a 1.14.x GKE version with a working workload identity feature  since they removed all of them. this is disastrous and i lost all day today trying to fix it to the point where all services stopped working due to some networking issues.

**Comment by jlewi** [comment]
@mareksuscak @mvisonneau are all pods affected?

@mareksuscak Do you have a pointer to the recommendation to downgrade to 1.13?

I have a 1.14.8-gke.2 and I was able to successfully deploy KF 0.7.0. 

Launching K8s jobs I started seeing problems with workload identity. In particular, I started to see gcloud commands timing out.

I started seeing some errors like the following in the node metadata server pods

```
W1112 18:34:23.515622       1 metadata.go:313] surfaceable error handling request, surfacing as (code 404, message "Not Found"), path="/computeMetadata/v1/instance/service-accounts/default/identity" : surfaceable error (status 404, message "Not Found"): no child ""
```

**Comment by mareksuscak** [comment]
@jlewi We were using `COS_CONTAINERD` image and that one turned out to be the culprit in our case. We ditched it and it's working just fine now.

**Comment by jlewi** [comment]
@mareksuscak thanks for the info.

**Comment by jlewi** [comment]
So it looks like 

* workload identity might currently not work with any VM images using containerd
* GKE node metadata server might have some instability under heavy load

**Comment by jlewi** [comment]
I'm closing this issue because I don't think there's anything actionable for us

**Comment by e-compagno** [comment]
Same issue here that started yesterday:

In a test container where `gcloud` has been installed with a service account and workload identity, the command `gcloud auth list` gives:
```
No credentialed accounts.

To login, run:
  $ gcloud auth login `ACCOUNT`
```
Nodes have version `1.16.15-gke.7800`.  It worth mentioning that the system worked perfectly for many months before yesterday.

Is there any update on the resolution?
