### ISSUE TITLE
kfctl_v1.2.0-0-gbc038f9_darwin.tar.gz unpack into binary version "v1.0.1-0-gf3edb9b"

### ISSUE THREAD

**Issue by AbelThorne** [kubeflow/kfctl#485]
Trying to install kubeflow 1.2 (and being stuck with errors), I realized that "kfctl version" gives "v1.0.1-0-gf3edb9b". 
I downloaded the darwin tar.gz avaible at this URL: https://github.com/kubeflow/kfctl/releases/download/v1.2.0/kfctl_v1.2.0-0-gbc038f9_darwin.tar.gz

Since there is a 1.2 tag for kfctl I suspect this is not an expected...

**Comment by moficodes** [comment]
I would look into your path setup. 

I just download the binary and I am getting the right version.

Could you check with 

```
which kfctl
```

And see if you are using the new kfctl you downloaded in your path?

**Comment by AbelThorne** [comment]
You're absolutely right! 🤦 
Completely forgot I installed it somewhere else... Sorry about that, closing the issue.
