### ISSUE TITLE
kfctl apply -f doesn't work with relative path; can't rerun on app.yaml

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kfctl#49]
Using commit:  6739cd076d8dd9911ce40b44137a98b2a68efcca

```
mkdir ${KFAPP}
cd ${KFAPP}
kfctl apply -f ./kfctl_gcp_iap.yaml 
Error: Cannot determine the object kind:  (kubeflow.error): Code 400 with message: could not fetch specified config ./kfctl_gcp_iap.yaml: relative paths require a module with a pwd
```

My expectation would be that it uses the directory of kfctl_gcp_iap.yaml 

We have lots of bugs about the kfctl semantics; can we refactor the code to make it easy to write a unittest that verifies all the different use cases?

/cc @swiftdiaries

**Comment by jlewi** [comment]
The logic in NewLoadKFAppFromURi
https://github.com/kubeflow/kubeflow/blob/6739cd076d8dd9911ce40b44137a98b2a68efcca/bootstrap/pkg/kfapp/coordinator/coordinator.go#L388

Looks like buggy and messy. The order in which it does this things (setting default values), CreateKfAppCfgFile looks brittle.

CreateKfAppCfgFile should only need to be called in the case of a remote URI; if its a local file then the CfgFile already exists.

There is unnecessary divergence between the code paths for the remote URIs and local URIs.

Here's how I think we should fix this.

1. Check if its a remote URI
1. If its a remote URI copy it to a local path by calling CreateCfgFile
1. At this point the remote URI and local cases should be on the same footing
1. We can then create the KFApp

1. Initializing the defaults should happen later; e.g in init or generate.

**Comment by jlewi** [comment]
https://github.com/kubeflow/kubeflow/pull/4275

**Comment by jlewi** [comment]
I didn't actually do anything to fix the issue so I'm guessing its still present.

**Comment by richardsliu** [comment]
This is what I see on the latest RC:
```
ricliu@ricliu-linux:~/demo/deploy$ kubectl apply -f ./kfctl_gcp_iap.yaml
error: unable to recognize "./kfctl_gcp_iap.yaml": no matches for kind "KfDef" in version "kfdef.apps.kubeflow.org/v1alpha1"
```

**Comment by richardsliu** [comment]
This is what I see on the latest RC:
```
Error: Cannot determine the object kind:  (kubeflow.error): Code 400 with message: could not fetch specified config ./kfctl_gcp_iap.yaml: relative paths require a module with a pwd
Usage:
  kfctl apply [all(=default)|k8s|platform] [flags]

Flags:
  -f, --file string   Static config file to use. Can be either a local path or a URL.
                      For example:
                      --file=https://raw.githubusercontent.com/kubeflow/kubeflow/master/bootstrap/config/kfctl_platform_existing.yaml
                      --file=kfctl_platform_gcp.yaml
  -h, --help          help for apply
  -V, --verbose       verbose output default is false

Cannot determine the object kind:  (kubeflow.error): Code 400 with message: could not fetch specified config ./kfctl_gcp_iap.yaml: relative paths require a module with a pwd
```

**Comment by lluunn** [comment]
error is from:
https://github.com/kubeflow/kubeflow/blob/aef7dd9be70c8be98f5096979c65e601a4d78777/bootstrap/cmd/kfctl/cmd/build.go#L43

It's using go-getter here: https://github.com/kubeflow/kubeflow/blob/1d811f737d7555782dbeab09eb88795a84aeded9/bootstrap/pkg/utils/k8utils.go#L136

And got this error: https://github.com/hashicorp/go-getter/blob/3f60ec5cfbb2a39731571b9ddae54b303bb0a969/detect_file.go#L19

**Comment by lluunn** [comment]
verified with 0.7rc6 that we can apply with `./kfctl_gcp_iap.yaml`
