### ISSUE TITLE
'kfctl' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by CameliaBenLaamari** [kubeflow/kfctl#499]
I'm following the official website [tutorial](https://www.kubeflow.org/docs/distributions/azure/deploy/install-kubeflow/) to deploy Kubeflow on Azure.
I followed all the steps and everything worked until I ran into this error:

![image](https://user-images.githubusercontent.com/76062686/126902485-58aab08f-6d4c-4c8c-87ea-b9088c85edd6.png)

Any idea what the problem might be and how to solve this?
I'm using Windows 10, and the kfctl file is in C:/Users/\<username>

**Comment by LasalJayawardena** [comment]
@CameliaBenLaamari Were you able to resolve this? I amalso facing this issue. I used WSL as well, but nothing seems to work.

**Comment by CameliaBenLaamari** [comment]
> @CameliaBenLaamari Were you able to resolve this? I amalso facing this issue. I used WSL as well, but nothing seems to work.

@LasalJayawardena I didn't solve it, I just used a deployed instance of Kubeflow that runs on a private server (provided by the project owner at the time). Apparently Kubeflow wasn't designed to run on Windows. Not sure why it didn't work on WSL, but you can check this thread for more help: https://github.com/kubeflow/kubeflow/issues/3735

**Comment by LasalJayawardena** [comment]
Thank you @CameliaBenLaamari for the reply!
