### ISSUE TITLE
kfctl should set name if not set based on the directory

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kfctl#52]
If  `metadata.Name` isn't set in `KFDef` spec isn't set then kfctl should try to infer it based on the directory of the config file.

This matches the semantics of 0.6 which used the directory name to infer name.

Furthermore this allows us to do something like this

```
mkdir ${KFAPP}
cd ${KFAPP}
kfctl apply -f https://.....
```
And get a deployment named ${KFAPP}

After we update kfctl we will need to update the KFDef files to remove Name so that we trigger this behavior.

**Comment by jlewi** [comment]
kfctl changes are in kubeflow/kubeflow#4287

**Comment by richardsliu** [comment]
This is verified in rc.2.
/close
