### ISSUE TITLE
[GCP] Auto set GPU type for node auto provisioner based on zone

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kfctl#59]
Cluster creation in GKE will fail if node-auto-provisioning is enabled and the zone doesn't have the GPUs listed in the node auto-provisioner available.

We should fix this so that kfctl picks good defaults. 

The behavior should be as follows

1.  If [autoprovisioning-config.enabled](https://github.com/kubeflow/manifests/blob/4d2939d6c1a5fd862610382fde130cad33bfef75/gcp/deployment_manager_configs/cluster-kubeflow.yaml#L73) is set in the config file kfctl should respect it
1. If [autoprovisioning-config.enabled] is not set then kfctl should infer sensible defaults

   * kfctl should check the zone to see if accelerators are available
   * If accelerators are available it should include them in the auto-provisioned pool
   * If not accelerators should be removed from the auto-provisioning settings

**Comment by jlewi** [comment]
Here's a couple pointers if someone is interested in picking this up.

* I think the relevant modifications would happen in [generateDMConfigs](https://github.com/kubeflow/kubeflow/blob/cfc6d8b1fe5901e699fbfd81d19d1967f71c3713/bootstrap/pkg/kfapp/gcp/gcp.go#L1321)

* We would want to use the GCE API to see which GPUs a user has quota for in the selected zone

* We should pick the most advanced GPU for which the user has quota or no GPU if the user has no GPU quota

**Comment by PatrickXYS** [comment]
Since GCP has moved out of kfctl, we can close the issue

/close
