### ISSUE TITLE
[GCP] test_endpoint is ready needs to deal with lets encrypt quota

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kfctl#63]
Our GCP test_enpoint is ready is failing because we don't provision SSL certificates because we run into lets encrypt rate limiting.

We can work around that by swapping out a self-signed certificate using this python code
https://github.com/kubeflow/testing/blob/6828c18feb5c632569460ecbee26d67e8c2a82c8/py/kubeflow/testing/util.py#L774

We should probably update our endpoint test to call that function.to swap out the cert

**Comment by PatrickXYS** [comment]
Since GCP has migrated out of kfctl and use gcp-blueprint instead, close the issue

/close
