### ISSUE TITLE
KFDef v1 - Define API, Conversion Logic, and Update Manifests

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kfctl#73]
In the next release we will want to change KFDef to v1 (from v1beta1).
The API should be largely unchanged.
Nontheless there's some work to be done to actually get all the code in place and update the manifests.

/cc @gabrielwen

**Comment by gabrielwen** [comment]
I think the majority of work is on cleaning weird deps in current codes.  Other than that it should be just adding a new converter.
