### ISSUE TITLE
Move kfctl py code into kubeflow/kfctl

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kfctl#77]
Related to #7 - move code for kfctl to kubeflow/kfctl

* We need to move the python code related to testing kfctl into kubeflow/kfctl
* We should create the directory py/kubeflow/kfctl and all code should live there 
* The kfctl related code in [py/kubeflow/kubeflow/ci](https://github.com/kubeflow/kubeflow/tree/master/py/kubeflow/kubeflow/ci) should move to [py/kubeflow/kfctl/ci]

 * Code in  kubeflow/kubeflow [testing/kfctl](https://github.com/kubeflow/kubeflow/tree/master/testing/kfctl) should move to [py/kubeflow/kfctl/ci] as well
* The E2E test workflow should be updated to use this code.
* If there is general code in [testing](https://github.com/kubeflow/kubeflow/tree/master/testing) that might be useful for other repos not just kubeflow/kfctl then we should consider moving it into the kubeflow/testing repo instead.

**Comment by jlewi** [comment]
@richardsliu has the python code moved over?

**Comment by jlewi** [comment]
@gabrielwen could you provide an update please?

**Comment by gabrielwen** [comment]
@jlewi I think I move all the code we need.  just need second pair of eyes to make sure of that.

**Comment by jlewi** [comment]
Thanks @gabrielwen . 

I took a quick look.

It looks like we still have code here
https://github.com/kubeflow/kubeflow/tree/master/py/kubeflow/kubeflow/ci

That is also here:
https://github.com/kubeflow/kfctl/tree/master/py/kubeflow/kfctl/testing/ci

Lets delete the code in kubeflow/kubeflow and then we can close this

**Comment by jlewi** [comment]
Fixed by #4577.
