### ISSUE TITLE
[GCP] Auto optimize GKE cluster size (machine type) based on quota

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kfctl#82]
Right now the default Kubeflow cluster settings for GKE are too big to fit into the GCP free quota tier.

It would be nice if kfctl could automatically check how much quota a user has and auto-size the cluster to fit into the quota.

See also kubeflow/kfctl#59 auto-optimizing node auto-provisioner settings

**Comment by PatrickXYS** [comment]
Since GCP has migrated out of kfctl and use gcp-blueprint instead, close the issue

/close
