### ISSUE TITLE
Run unit test during presubmit

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kfctl#86]
We should run unit test like:
https://github.com/kubeflow/kubeflow/blob/v0.7-branch/testing/workflows/components/unit_tests.jsonnet#L123

**Comment by kunmingg** [comment]
@gabrielwen @jlewi

**Comment by gabrielwen** [comment]
Duplicate of #26 ?

**Comment by kunmingg** [comment]
Feel free to close one, thanks
