### ISSUE TITLE
kubeflow/kfctl presubmits broken by moving code to kubeflow/kfctl 

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kfctl#91]
The kubeflow/kfctl presubmits are currently broken. 

This is because the presubmits in kubeflow/kfctl were actually  using the code in kubeflw/kubeflow

The code in kubeflow/kubeflow was deleted in kubeflow/kubeflow#4485. As a result the kubeflow/kfctl tests are failing because they are trying to build kubeflow using source code that no longer exists.

related to: kubeflow/kfctl#7 make kubeflow/kfctl the source of truth for development

**Comment by gabrielwen** [comment]
presubmit is fixed.
/close
