### ISSUE TITLE
Convert tests in kfctl_e2e_workflow.py to pytest

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/kfctl#97]
https://github.com/kubeflow/kfctl/blob/master/py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py#L362

**Comment by gabrielwen** [comment]
For all the tests running with `python -m` we should convert them into pytest format.

**Comment by gabrielwen** [comment]
@amalts do you think this is an interesting task?

there are 2 sub-tasks in this issue:
- Fix pytorch and notebook tests and re-enable them in presubmits.
- Transform tests that are run with `python -m` to be [pytests](https://github.com/kubeflow/kfctl/tree/master/py/kubeflow/kfctl/testing/pytests)

**Comment by amalts** [comment]
@gabrielwen Definitely ! I can take this up.

**Comment by gabrielwen** [comment]
thanks!

**Comment by amalts** [comment]
@gabrielwen Sorry for not following up on this. It took more time for me to get some insights into the test infra before starting.

**Comment by gabrielwen** [comment]
@amalts that's ok.  sorry that I had to take over and finish this issue - we need to guard the testing coverage.

/close
