### ISSUE TITLE
kfctl binary releases for different platforms

### ISSUE THREAD

**Issue by MrXinWang** [kubeflow/kfctl#99]
Referencing [issue#2337](https://github.com/kubeflow/kubeflow/issues/2337) and discussions in [issue#4433](https://github.com/kubeflow/kubeflow/issues/4133), is it possible to release a binary of kfctl for different platforms? Thanks.

**Comment by yanniszark** [comment]
Since Go compiles completely static binaries and changing the target platform is as simple as changing an environment variable (GOARCH), I would expect that this is easily possible, at lease for programs written in Go, like kfctl.

**Comment by MrXinWang** [comment]
Hi @yanniszark ! Late to the party :P I have created PR #318 for arm64 building. Could you please take a look? Thank you very much!

**Comment by MrXinWang** [comment]
Closing this as PR #318 has been merged.
